#!/usr/bin/env python3
import re
from pathlib import Path

import com.emprogen.subprocess_functions as spf
import com.emprogen.java.maven.java_maven_functions as jmf
import com.emprogen.file_functions as filef
from com.emprogen.java.maven.models import Gav

AUTHOR_DEFAULT = 'Generated by Emprogen'
# the package.Classname of a tool used to generate a java impl Class given a java Interface.
GEN_IMPL_CLASS = "com.emprogen.generate.impl.GenerateImplService"
# the maven gav for the GenerateImplService tool.
GENERATE_IMPL_GAV = "com.emprogen:generate-impl:0.0.2"
# the directory com/emprogen/java/maven
JAVA_MAVEN_DIR = jmf.get_java_maven_path()
# the location of the script that gets maven dependencies for calling from classpath context
MAVEN_CP_PY = JAVA_MAVEN_DIR / 'maven_cp.py'
# get the maven dependencies for the module containing the tool used to generate a java impl Class given a java Interface.
GENERATE_IMPL_CLASSPATH = spf.run_subprocess_capture_output(
    [MAVEN_CP_PY, GENERATE_IMPL_GAV]
).strip()

THIS_SCRIPT_PATH = filef.get_file_path(__file__)

# get the text of the impl_template and store it in a variable.
IMPL_TEMPLATE_TEXT = (THIS_SCRIPT_PATH / 'impl_template.txt').read_text(encoding='utf-8')
# get the text of the service_template and store it in a variable.
SERVICE_TEMPLATE_TEXT = (THIS_SCRIPT_PATH / 'service_template.txt').read_text(encoding='utf-8')
# get the text of the impl_template_test and store it in a variable.
IMPL_TEMPLATE_TEST_TEXT = (THIS_SCRIPT_PATH / 'impl_test_template.txt').read_text(encoding='utf-8')
# get the text of the service_template_test and store it in a variable.
SERVICE_TEMPLATE_TEST_TEXT = (THIS_SCRIPT_PATH / 'service_test_template.txt').read_text(encoding='utf-8')


def process_api_interfaces(
    api_gav: Gav,
    proj_gav: Gav,
    api_interface_list: list,
    *,
    author: str = AUTHOR_DEFAULT
) -> str:
    print(f'api_interface_list: {api_interface_list}')
    # get the maven dependencies for the module containing the jaxrs Interface from which the service will be generated.
    service_implementation_classpath = spf.run_subprocess_capture_output([str(MAVEN_CP_PY), str(api_gav)]).strip()
    print (f'service_implementation_classpath: {service_implementation_classpath}')

    # the java package for the project to be generated.
    generated_package = jmf.get_package(proj_gav)

    # the directory of the java code.
    model_path = jmf.get_model_path(proj_gav)
    test_model_path = jmf.get_test_model_path(proj_gav)

    for api_interface_string in api_interface_list:
        process_api_interface(
            api_interface_string,
            generated_package, api_gav,
            model_path,
            test_model_path,
            service_implementation_classpath,
            author=author
        )

    remove_template_placeholder_files(model_path, test_model_path)

    return service_implementation_classpath


def process_api_interface(
    service_interface_name: str,
    generated_package: str,
    service_interface_gav: Gav,
    model_path: Path,
    test_model_path: Path,
    service_implementation_classpath: str,
    *,
    author: str = AUTHOR_DEFAULT
) -> None:
    """
    Take the impl code generated from the interface.
    Process to create method code for Impl and Service Classes.
    Write that text to the respective files on the file system.
    """
    # Run the tool to get the generated code from the jaxrs Interface.
    # This code is shared between both the service Impl class and the service class.
    generated_impl = generate_impl(
        service_interface_name,
        generated_package,
        service_implementation_classpath
    )
    print(f'generated_impl: {generated_impl}')

    method_name_to_method_dict = get_method_name_to_method_dict(generated_impl)
    method_to_args_dict = get_method_to_args_dict(
        method_name_to_method_dict.keys(),
        generated_impl
    )

    service_interface_name_without_package = service_interface_name.split('.')[-1]

    jaxrs_service_package = jmf.get_package(service_interface_gav)
    # the generated content for the service Impl class,
    # with the methods calling the service from the Impl class.
    impl_class_str = impl_template_replacment(
        generated_package,
        service_interface_name_without_package,
        jaxrs_service_package,
        author=author
    )
    service_interface_impl = generate_service_interface_impl(
        method_name_to_method_dict,
        method_to_args_dict,
        impl_class_str
    )

    # the generated content for the service class
    service_class_str = service_template_replacement(
        generated_package,
        service_interface_name_without_package,
        author=author
    )
    service_class_delegate = generate_service_class_delegate(
        method_name_to_method_dict.values(),
        service_class_str
    )

    # the generated content for the service Impl test class
    impl_class_test_str = impl_template_test_replacement(
        generated_package,
        service_interface_name_without_package,
        author=author
    )
    service_interface_impl_test = generate_service_interface_impl_test(
        impl_class_test_str
    )

    # the generated content for the service test class
    service_class_test_str = service_template_test_replacement(
        generated_package,
        service_interface_name_without_package,
        author=author
    )
    service_class_delegate_test = generate_service_class_delegate_test(
        service_class_test_str
    )

    # the template java impl class file.
    impl_template_file_path = model_path / 'impl'
    impl_template_file_name = service_interface_name_without_package + 'Impl.java'

    # the template java bean class file.
    service_template_file_path = model_path
    service_template_file_name = service_interface_name_without_package + 'Service.java'

    # the template java impl test class file.
    impl_template_test_file_path = test_model_path / 'impl'
    impl_template_test_file_name = service_interface_name_without_package + 'ImplTest.java'

    # the template java bean test class file.
    service_template_test_file_path = test_model_path
    service_template_test_file_name = service_interface_name_without_package + 'ServiceTest.java'

    # Write files to their respective locations on the file system.
    filef.make_file(
        impl_template_file_path / Path(impl_template_file_name), 
        file_content=service_interface_impl
    )

    filef.make_file(
        service_template_file_path / Path(service_template_file_name), 
        file_content=service_class_delegate
    )

    filef.make_file(
        impl_template_test_file_path / Path(impl_template_test_file_name),
        file_content=service_interface_impl_test
    )

    filef.make_file(
        service_template_test_file_path / Path(service_template_test_file_name),
        file_content=service_class_delegate_test
    )


# Take the class content stub for the Impl class and add the processed method code to it,
# replacing the 'return null;' in the method stubs with 'return service.method(args)'.
def generate_service_interface_impl(
    method_name_to_method_dict: dict,
    method_to_args_dict: dict,
    impl_class_str: str
) -> str:
    modified_methods_list = []
    # replace methods' 'return null;' with 'return service.method(args)'.
    for method_name, method_string in method_name_to_method_dict.items():
        call_string = f'service.{method_name}({method_to_args_dict[method_name]})'
        modified_methods_list.append(method_string.replace('null', call_string))

    impl_methods = '\n\n'.join(modified_methods_list) + '\n\n'
    # print (f'impl_methods: {impl_methods}'

    # write methods into Impl class and return
    #TODO check re.sub(r'\}\s*$',
    return re.sub('}', impl_methods + '}', impl_class_str)


# Take the class content stub for the Service class and add the processed method code to it.
def generate_service_class_delegate(method_list: list, service_class_str: str) -> str:
    methods = '\n\n'.join(method_list) + '\n\n'
    # print ('methods: ' + str(methods))

    # strip @Overrides from generated code methods
    # write stripped methods into service class string and return
    return re.sub('}', methods.replace('@Override\n', '') + '}', service_class_str)


def generate_service_interface_impl_test(impl_class_test_str: str) -> str:
    # TODO
    return impl_class_test_str


def generate_service_class_delegate_test(service_class_test_str: str) -> str:
    # TODO
    return service_class_test_str


def impl_template_replacment(
    package: str,
    jaxrs_service_interface: str,
    jaxrs_service_package: str,
    *,
    author: str = AUTHOR_DEFAULT
) -> str:
    """
    Returns the text of the impl template file, with the text substituted with params.
    jaxrs_service_interface is name only, without package.
    """
    return (
        IMPL_TEMPLATE_TEXT
        .replace('${package}', package)
        .replace('${jaxrs_service_interface}', jaxrs_service_interface)
        .replace('${jaxrs_service_package}', jaxrs_service_package)
        .replace('${author}', author)
    )


def service_template_replacement(
    package: str,
    jaxrs_service_interface: str,
    *,
    author: str = AUTHOR_DEFAULT
) -> str:
    """
    Returns the text of the service template file, with the text substituted with params.
    jaxrs_service_interface is name only, without package.
    """
    return (
        SERVICE_TEMPLATE_TEXT
        .replace('${package}', package)
        .replace('${jaxrs_service_interface}', jaxrs_service_interface)
        .replace('${author}', author)
    )


def impl_template_test_replacement(
    package: str,
    jaxrs_service_interface: str,
    *,
    author: str = AUTHOR_DEFAULT
) -> str:
    """
    Returns the text of the impl template test file, with the text substituted with params.
    jaxrs_service_interface is name only, without package.
    """
    return (
        IMPL_TEMPLATE_TEST_TEXT
        .replace('${package}', package)
        .replace('${jaxrs_service_interface}', jaxrs_service_interface)
        .replace('${author}', author)
    )


def service_template_test_replacement(
    package: str,
    jaxrs_service_interface: str,
    *,
    author: str = AUTHOR_DEFAULT
) -> str:
    """
    Returns the text of the service template test file, with the text substituted with params.
    jaxrs_service_interface is name only, without package.
    """
    return (
        SERVICE_TEMPLATE_TEST_TEXT
        .replace('${package}', package)
        .replace('${jaxrs_service_interface}', jaxrs_service_interface)
        .replace('${author}', author)
    )


def remove_template_placeholder_files(model_path: Path, test_model_path: Path) -> None:
    filef.delete_file(model_path / Path('TemplateService.java'))
    filef.delete_file(model_path / Path('impl') / Path('TemplateImpl.java'))

    filef.delete_file(test_model_path / Path('TemplateServiceTest.java'))
    filef.delete_file(test_model_path / Path('impl') / Path('TemplateImplTest.java'))


def is_class_file_an_api_definition(class_file_content: str) -> bool:
    has_api_def_ann = False
    is_interface = False
    match = re.search(
        r'org.eclipse.microprofile.openapi.annotations.OpenAPIDefinition',
        class_file_content
    )
    if match:
        has_api_def_ann = True
    if 'public interface' in class_file_content:
        is_interface = True
    return has_api_def_ann and is_interface


def generate_impl(
    service_interface_name: str,
    generated_package: str,
    service_implementation_classpath: str) -> str:
    # run the tool to get the generated code from the jaxrs Interface.
    classpath = f"{service_implementation_classpath}:{GENERATE_IMPL_CLASSPATH}"
    cmd = [
        'java',
        '-cp',
        classpath,
        GEN_IMPL_CLASS,
        service_interface_name,
        generated_package
    ]
    return spf.run_subprocess_capture_output(cmd)


def get_method_name_to_method_dict(generated_impl: str) -> dict:
    # get methods code from generated code
    pattern = re.compile(r'(\s{4}@Override(\n|.)+?})')
    matches = re.finditer(pattern, generated_impl)
    match_list = [match.group() for match in matches]
    # print (f'match_list: {match_list}')

    # get method names from generated code
    # methods will be \s methodName[\s zero or more whitespace, then left parentheses. (]
    method_name_pattern = re.compile(r'(?<=\s)([a-zA-Z0-9$_]+)(?=\s*\()')
    method_name_matches = re.finditer(method_name_pattern, generated_impl)
    method_name_match_list = [match.group() for match in method_name_matches]
    # print (f'method_name_match_list: {method_name_match_list}')

    method_name_to_method_dict = dict(zip(method_name_match_list, match_list))
    return method_name_to_method_dict


def get_method_to_args_dict(
    method_name_match_list: list,
    generated_impl: str
) -> dict:
    # get the arg list for each method
    arg_match_list = []

    for method_name in method_name_match_list:
        # get the arg list for the method
        arg_pattern = re.compile(r'(?<=\s)' + method_name + '\s*\((.*?)\)')
        arg_match = re.search(arg_pattern, generated_impl)
        if None != arg_match:
            arg_match_list.append(arg_match.group(1))
        # print(f'arg_match_list: {arg_match_list}')

    # dict of methodName:rawArgList
    method_to_args_dict = dict(zip(method_name_match_list, arg_match_list))
    print (f'method_to_args_dict: {method_to_args_dict}')

    # parse the args to remove types.
    for method_name, arg_list in method_to_args_dict.items():
        print (f'method_name: {method_name}')
        print (f'arg_list: {arg_list}')
        # get the arg type:value pairs
        arg_type_var_list = arg_list.split(',')
        # print (f'arg_type_var_list: {arg_type_var_list}')
        # get the arg var names
        arg_vars = []
        for arg_type_var in arg_type_var_list:
            # print (f'arg_type_var: {arg_type_var}')
            arg_array_tmp = arg_type_var.strip().split(' ')
            if len(arg_array_tmp) > 1:
                arg_vars.append(arg_array_tmp[1])
        # print (f'arg_vars: {arg_vars}')

        method_to_args_dict[method_name] = ', '.join(arg_vars)

    print (f'method_to_args_dict2: {method_to_args_dict}')
    return method_to_args_dict


print(f'loaded {__file__}')

if __name__ == '__main__':
    # test code here
    #callMvnWithOptions(**{'A': 'a', 'B': 'b', 'C': 'c'}, goal='version')
    cwd=os.getcwd()
    print('cwd:' + cwd)
    