import re
import com.emprogen.java.maven.functions as jmf

# the package.Classname of a tool used to generate a java impl Class given a java Interface.
genImplClass = "com.emprogen.generate.impl.GenerateImplService"
# the maven gav for the GenerateImplService tool.
generateImplGav = "com.emprogen:generate-impl:0.0.2"
# the directory com/emprogen/java/maven
javaMavenDir = jmf.getJavaMavenPath()
# the location of the script that gets maven dependencies for calling from classpath context
cpPlUrl=javaMavenDir + '/maven-cp.py'
# get the maven dependencies for the module containing the tool used to generate a java impl Class given a java Interface.
generateImplClasspath = jmf.runSubprocessCaptureOutput([cpPlUrl, generateImplGav]).strip()

thisScriptPath = jmf.getFilePath(__file__)

# get the text of the impl_template and store it in a variable.
impl_template_text = ''
with open(thisScriptPath + '/impl_template.txt', 'r') as f:
    impl_template_text = f.read()

# get the text of the service_template and store it in a variable.
service_template_text = ''
with open(thisScriptPath + '/service_template.txt', 'r') as f:
    service_template_text = f.read()

# get the text of the impl_template_test and store it in a variable.
impl_template_test_text = ''
with open(thisScriptPath + '/impl_test_template.txt', 'r') as f:
    impl_template_test_text = f.read()

# get the text of the service_template_test and store it in a variable.
service_template_test_text = ''
with open(thisScriptPath + '/service_test_template.txt', 'r') as f:
    service_template_test_text = f.read()


def processApiInterfaces(apiGav: 'Gav', projGav: 'Gav', apiInterfaceList: 'list', *, author: 'str' = 'Generated by Emprogen') -> 'str':
    print( 'apiInterfaceList: ' + str(apiInterfaceList))
    # get the maven dependencies for the module containing the jaxrs Interface from which the service will be generated.
    serviceImplementationClasspath = jmf.runSubprocessCaptureOutput([cpPlUrl, str(apiGav)]).strip()
    print ('serviceImplementationClasspath: ' + str(serviceImplementationClasspath))

    # the java package for the project to be generated.
    generatedPackage = jmf.getPackage(projGav)

    # the directory of the java code.
    modelPath = jmf.getModelPath(projGav)
    testModelPath = modelPath.replace('/src/main/java/', '/src/test/java/', 1)

    for apiInterfaceString in apiInterfaceList:
        processApiInterface(apiInterfaceString, generatedPackage, apiGav, modelPath, testModelPath, serviceImplementationClasspath, author=author)

    removeTemplatePlaceholderFiles(modelPath, testModelPath)

    return serviceImplementationClasspath

# Take the impl code generated from the interface.
# Process to create method code for Impl and Service Classes.
# Write that text to the respective files on the file system.
def processApiInterface(serviceInterfaceName: 'str', generatedPackage: 'str', serviceInterfaceGav: 'Gav', modelPath: 'str', 
        testModelPath: 'str', serviceImplementationClasspath: 'str', *, author: 'str' = 'Generated by Emprogen', ) -> None:

    # Run the tool to get the generated code from the jaxrs Interface.
    # This code is shared between both the service Impl class and the service class.
    generatedImpl = generateImpl(serviceInterfaceName, generatedPackage, serviceImplementationClasspath)
    print('generatedImpl: ' + str(generatedImpl))

    methodNameToMethodDict = getMethodNameToMethodDict(generatedImpl)
    methodToArgsDict = getMethodToArgsDict(methodNameToMethodDict.keys(), generatedImpl)

    serviceInterfaceNameWithoutPackage = serviceInterfaceName.split('.')[-1]

    jaxrsServicePackage = jmf.getPackage(serviceInterfaceGav)
    # the generated content for the service Impl class, with the methods calling the service from the Impl class.
    implClassStr = implTemplateReplacment(generatedPackage, serviceInterfaceNameWithoutPackage, jaxrsServicePackage, author=author)
    serviceInterfaceImpl = generateServiceInterfaceImpl(methodNameToMethodDict, methodToArgsDict, implClassStr)

    # the generated content for the service class
    serviceClassStr = serviceTemplateReplacment(generatedPackage, serviceInterfaceNameWithoutPackage, author=author)
    serviceClassDelegate = generateServiceClassDelegate(methodNameToMethodDict.values(), serviceClassStr)

    # the generated content for the service Impl test class
    implClassTestStr = implTemplateTestReplacment(generatedPackage, serviceInterfaceNameWithoutPackage, author=author)
    serviceInterfaceImplTest = generateServiceInterfaceImplTest(implClassTestStr)

    # the generated content for the service test class
    serviceClassTestStr = serviceTemplateTestReplacment(generatedPackage, serviceInterfaceNameWithoutPackage, author=author)
    serviceClassDelegateTest = generateServiceClassDelegateTest(serviceClassTestStr)

    # the template java impl class file.
    implTemplateFilePath = modelPath + '/impl/'
    implTemplateFileName = serviceInterfaceNameWithoutPackage + 'Impl.java'

    # the template java bean class file.
    serviceTemplateFilePath = modelPath + '/'
    serviceTemplateFileName = serviceInterfaceNameWithoutPackage + 'Service.java'

    # the template java impl test class file.
    implTemplateTestFilePath = testModelPath + '/impl/'
    implTemplateTestFileName = serviceInterfaceNameWithoutPackage + 'ImplTest.java'

    # the template java bean test class file.
    serviceTemplateTestFilePath = testModelPath + '/'
    serviceTemplateTestFileName = serviceInterfaceNameWithoutPackage + 'ServiceTest.java'

    # Write files to their respective locations on the file system.
    jmf.makeFile(implTemplateFilePath, implTemplateFileName)
    jmf.replaceFileContents(serviceInterfaceImpl, implTemplateFilePath + implTemplateFileName)

    jmf.makeFile(serviceTemplateFilePath, serviceTemplateFileName)
    jmf.replaceFileContents(serviceClassDelegate, serviceTemplateFilePath + serviceTemplateFileName)

    jmf.makeFile(implTemplateTestFilePath, implTemplateTestFileName)
    jmf.replaceFileContents(serviceInterfaceImplTest, implTemplateTestFilePath + implTemplateTestFileName)

    jmf.makeFile(serviceTemplateTestFilePath, serviceTemplateTestFileName)
    jmf.replaceFileContents(serviceClassDelegateTest, serviceTemplateTestFilePath + serviceTemplateTestFileName)


# Take the class content stub for the Impl class and add the processed method code to it,
# replacing the 'return null;' in the method stubs with 'return service.method(args)'.
def generateServiceInterfaceImpl(methodNameToMethodDict: 'dict', methodToArgsDict: 'dict', implClassStr: 'str') -> 'str':
    modifiedMethodsList = []
    # replace methods' 'return null;' with 'return service.method(args)'.
    for methodName, methodString in methodNameToMethodDict.items():
        callString = 'service.' + methodName + '(' + methodToArgsDict[methodName] + ')'
        modifiedMethodsList.append(methodString.replace('null', callString))

    implMethods = '\n\n'.join(modifiedMethodsList) + '\n\n'
    # print ('implMethods: ' + str(implMethods))

    # write methods into Impl class and return
    return re.sub('}', implMethods + '}', implClassStr)

# Take the class content stub for the Service class and add the processed method code to it.
def generateServiceClassDelegate(methodList: 'list', serviceClassStr: 'str') -> 'str':
    methods = '\n\n'.join(methodList) + '\n\n'
    # print ('methods: ' + str(methods))

    # strip @Overrides from generated code methods
    # write stripped methods into service class string and return
    return re.sub('}', methods.replace('@Override\n', '') + '}', serviceClassStr)

def generateServiceInterfaceImplTest(implClassTestStr: 'str') -> 'str':
    return implClassTestStr

def generateServiceClassDelegateTest(serviceClassTestStr: 'str') -> 'str':
    return serviceClassTestStr

# Returns the text of the impl template file, with the text substituted with params.
# jaxrs service interface is name only, without package.
def implTemplateReplacment(package: 'str', jaxrs_service_interface: 'str', jaxrs_service_package: 'str', *, author: 'str' = 'Generated by Emprogen') -> 'str':
    return impl_template_text.replace('${package}', package).replace('${jaxrs_service_interface}', jaxrs_service_interface).replace('${jaxrs_service_package}', jaxrs_service_package).replace('${author}', author)

# Returns the text of the service template file, with the text substituted with params.
# jaxrs service interface is name only, without package.
def serviceTemplateReplacment(package: 'str', jaxrs_service_interface: 'str', *, author: 'str' = 'Generated by Emprogen') -> 'str':
    return service_template_text.replace('${package}', package).replace('${jaxrs_service_interface}', jaxrs_service_interface).replace('${author}', author)

# Return the text of the impl template test file, with the text substituted with params.
# jaxrs service interface is name only, without package.
def implTemplateTestReplacment(package: 'str', jaxrs_service_interface: 'str', *, author: 'str' = 'Generated by Emprogen') -> 'str':
    return impl_template_test_text.replace('${package}', package).replace('${jaxrs_service_interface}', jaxrs_service_interface).replace('${author}', author)

# Return the text of the service template test file, with the text substituted with params.
# jaxrs service interface is name only, without package.
def serviceTemplateTestReplacment(package: 'str', jaxrs_service_interface: 'str', *, author: 'str' = 'Generated by Emprogen') -> 'str':
    return service_template_test_text.replace('${package}', package).replace('${jaxrs_service_interface}', jaxrs_service_interface).replace('${author}', author)

def removeTemplatePlaceholderFiles(modelPath: 'str', testModelPath: 'str') -> None:
    jmf.deleteFile(modelPath + '/TemplateService.java')
    jmf.deleteFile(modelPath + '/impl/TemplateImpl.java')

    jmf.deleteFile(testModelPath + '/TemplateServiceTest.java')
    jmf.deleteFile(testModelPath + '/impl/TemplateImplTest.java')

def isClassFileAnApiDefinition(classFileContent: 'str') -> bool:
    hasApiDefAnn = False
    isInterface = False
    if 'org.eclipse.microprofile.openapi.annotations.OpenAPIDefinition' in classFileContent:
        hasApiDefAnn = True
    if 'public interface' in classFileContent:
        isInterface = True
    return hasApiDefAnn and isInterface

def generateImpl(serviceInterfaceName: 'str', generatedPackage: 'str', serviceImplementationClasspath: 'str') -> 'str':
    # run the tool to get the generated code from the jaxrs Interface.
    return jmf.runSubprocessCaptureOutput(['java', '-cp', 
            serviceImplementationClasspath + ':' + generateImplClasspath, genImplClass, 
            serviceInterfaceName, generatedPackage])

def getMethodNameToMethodDict(generatedImpl: 'str') -> 'dict':
    # get methods code from generated code
    pattern = re.compile(r'(\s{4}@Override(\n|.)+?})')
    matches = re.finditer(pattern, generatedImpl)
    matchList = [match.group() for match in matches]
    # print ('matchList: ' + str(matchList))

    # get method names from generated code
    # methods will be \s methodName[\s zero or more whitespace, then left parentheses. (]
    methodNamePattern = re.compile(r'(?<=\s)([a-zA-Z0-9$_]+)(?=\s*\()')
    methodNameMatches = re.finditer(methodNamePattern, generatedImpl)
    methodNameMatchList = [match.group() for match in methodNameMatches]
    # print ('methodNameMatchList: ' + str(methodNameMatchList))

    methodNameToMethodDict = dict(zip(methodNameMatchList, matchList))
    return methodNameToMethodDict

def getMethodToArgsDict(methodNameMatchList: 'list', generatedImpl: 'str') -> 'dict':
    # get the arg list for each method
    argMatchList = []

    for methodName in methodNameMatchList:
        # get the arg list for the method
        argPattern = re.compile(r'(?<=\s)' + methodName + '\s*\((.*?)\)')
        argMatch = re.search(argPattern, generatedImpl)
        if None != argMatch:
            argMatchList.append(argMatch.group(1))
        # print ('argMatchList: ' + str(argMatchList))

    # dict of methodName:rawArgList
    methodToArgsDict = dict(zip(methodNameMatchList, argMatchList))
    print ('methodToArgsDict: ' + str(methodToArgsDict))

    # parse the args to remove types.
    for methodName, argList in methodToArgsDict.items():
        print ('methodName: ' + methodName)
        print ('argList: ' + argList)
        # get the arg type:value pairs
        argTypeVarList = argList.split(',')
        # print ('argTypeVarList: ' + str(argTypeVarList))
        # get the arg var names
        argVars = []
        for argTypeVar in argTypeVarList:
            # print ('argTypeVar: ' + argTypeVar)
            argArrayTmp = argTypeVar.strip().split(' ')
            if len(argArrayTmp) > 1:
                argVars.append(argArrayTmp[1])
        # print ('argVars: ' + str(argVars))

        methodToArgsDict[methodName] = ', '.join(argVars)

    print ('methodToArgsDict2: ' + str(methodToArgsDict))
    return methodToArgsDict

print('loaded ' + __file__)

if __name__ == '__main__':
    # test code here
    #callMvnWithOptions(**{'A': 'a', 'B': 'b', 'C': 'c'}, goal='version')
    cwd=os.getcwd()
    print('cwd:' + cwd)
    