%YAML 1.1
---
$schema: "http://stsci.edu/schemas/yaml-schema/draft-01"
id: "http://emprogen.com/schemas/java/maven/api/openapi/swagger/jaxrs/p5/v8/javax/schema"
tag: "tag:emprogen.com:java/maven/api/openapi/swagger/jaxrs/p5/v8/javax/schema"
title: |
  Schema for yaml defining openapi jaxrs generation.
description: |
  This schema is for yaml descriptors defining generation of jaxrs interfaces from openapi.
examples:
  - |
    id: com.emprogen.java.maven.api.openapi.swagger.jaxrs.p5.v8.javax
    generatedGav: com.github.mshin:example-api:1.0.0
    author: MunChul Shin
    openApiUrl:
type: object
properties:
  id:
    type: string
    pattern: "^[\\w\\.\\-]+$"
    description: |
      The unique path to the generate script. '.' delimited.
  generatedGav:
    type: string
    pattern: "^[\\w\\-\\$\\.]+:[\\w\\-\\$\\.]+(:.+|)$"
    description: |
      The maven GAV (groupId:artifactId:version) for the generated code.
  author:
    type: string
    description: |
      The person who authored the code.
  openApiUrl:
    type: string
    # pattern: ""
    description: |
      The path to the URL where the OpenAPI document is located.
  dependencyGav:
    type: array
    description: |
      A list of dependency GAVs to add to the generated projects' pom.
    items:
      type: string
      pattern: "^[\\w\\-\\$\\.]+:[\\w\\-\\$\\.]+:[\\w\\-\\$\\.]+$"
required: [id, generatedGav]
additionalProperties: false