import com.emprogen.java.maven.functions as jmf
import com.emprogen.java.maven.yaml_functions as yf
import com.emprogen.java.maven.field_functions as ff
import com.emprogen.java.maven.service.jaxrs.service_impl_functions as sif
import com.emprogen.prepend_license as pl
import glob
import re

from com.emprogen.java.maven.models import Gav

def generate(descriptor: 'dict', archetypeGav: 'Gav' = Gav('com.emprogen', 'service-jaxrs-quarkus-p1-archetype', '0.0.2')
        , *, filesPath: 'str' = None, javaVersion: 'str' = '17', **kwargs) -> None:

    print('in service.jaxrs.quarkus.p2.v1.generate.py')
    print('javaVersion: ' + str(javaVersion))

    # define maven archetype used for this generator within script.
    arch_gav = archetypeGav

    # the maven groupId:artifactId:version for the code module to be generated
    proj_gav = yf.getGeneratedProjectGav(descriptor)

    # the gav for the maven module containing the jaxrs Interface from which the service will be generated.
    service_interface_gav_string = descriptor['serviceInterfaceGav']
    api_gav = yf.getGav(service_interface_gav_string)

    # the directory of the maven pom for the generated code. Usually at the directory root of project.
    proj_pom_path = proj_gav.artifact_id + '/pom.xml'

    author = descriptor.get('author', 'Generated by Emprogen')

    # Geneate Maven project.
    # Set Maven archetype generation options.
    opts = {}
    opts['api_groupId'] = api_gav.group_id
    opts['api_artifactId'] = api_gav.artifact_id
    opts['api_version'] = api_gav.version
    opts['jaxrs_service_interface'] = 'Template'
    opts['jaxrs_service_package'] = 'does.not.matter'
    print('service opts: ' + str(opts))

    #Enable mvn opts from command line
    mvn_options = jmf.captureContextualCommandLineOptions(kwargs.get('command_args', []), 'mvn')
    mvn_opts = {'mvn_options': mvn_options}
    opts.update(mvn_opts)

    print('mvn_options: ' + str(mvn_options))
    print('opts: ' + str(opts))

    # Actually generate the maven project
    jmf.generateMavenProject(arch_gav, proj_gav, author, **opts)
    print('Generated maven project with archetype: ' + str(arch_gav) + ' and projGav: ' + str(proj_gav))

    # get the java files, then winnow to ApiDefinition files.
    api_definition_files = []

    # get the gav from the serviceInterfaceGav (apiGav) and load the jar.
    # return a list of java class files in the jar that match the apiGav.
    api_gav_path = jmf.gav_to_path(str(api_gav))
    api_gav_class_files = jmf.getFilesFromJar(api_gav_path, extensionFilter='.class')
    api_gav_class_file_contents = {}
    print('apiGavClassFiles: ' + str(api_gav_class_files))

    # Create a dictionary mapping from the java class name to the content of the class file for each java class file in the apiGav jar.
    for api_gav_class_file in api_gav_class_files:
        java_class_name = api_gav_class_file.replace('/', '.').replace('.class', '')
        print('javaClassName: ' + str(java_class_name))
        content_from_jar_class = jmf.readContentFromJarClass(api_gav_path, java_class_name)
        print('contentFromJarClass: ' + str(content_from_jar_class))
        api_gav_class_file_contents[java_class_name] = content_from_jar_class
    #print('apiGavClassFileContents: ' + str(apiGavClassFileContents))

    # Iterate over the java class file contents and find the ones that are ApiDefinition files.
    for class_name, class_file_content in api_gav_class_file_contents.items():
        print('Checking if class is API definition: ' + str(class_name))
        if sif.isClassFileAnApiDefinition(class_file_content):
            print('Found API definition: ' + str(class_name))
            api_definition_files.append(class_name)

    print('apiDefinitionFiles: ' + str(api_definition_files))

    # process the API definition files to generate the service Impl and service classes.
    service_implementation_classpath = sif.processApiInterfaces(api_gav, proj_gav, api_definition_files, author=author)

    # add addtl dependencies to the pom.
    # if no items in optional dependencyGav, default {} for null safety
    for dependency in descriptor.get('dependencyGav', {}):
        print('adding dependency to pom: ' + dependency)
        jmf.addDependency(proj_pom_path, yf.getGav(dependency))

    # set java version to javaVersion
    maven_compiler_source = 'maven.compiler.source'
    maven_compiler_target = 'maven.compiler.target'
    jmf.removePomProperties(proj_pom_path, [maven_compiler_source, maven_compiler_target])
    jmf.addPomProperties(proj_pom_path, {maven_compiler_source: javaVersion, maven_compiler_target: javaVersion})

    # set jaxrs package and java version based on the openapi3 module
    if None != re.search('javax.ws.rs.javax.ws.rs-api', service_implementation_classpath):
        print('Using javax in API definition module. Reducing Quarkus version in impl module to use javax instad of jakarta code packages. Reducing java version to 8.')
        # Fix java imports
        for java_file in javaClassFilePaths:
            jmf.replaceTextInFile('import jakarta.', 'import javax.', java_file)
        # Reduce Quarkus version
        jmf.removePomProperties(proj_pom_path, ['version.quarkus'])
        jmf.addPomProperties(proj_pom_path, {'version.quarkus': '2.16.8.Final'})

        # Reduce Java version to 8
        jmf.removePomProperties(proj_pom_path, [maven_compiler_source, maven_compiler_target])
        jmf.addPomProperties(proj_pom_path, {maven_compiler_source: '8', maven_compiler_target: '8'})

    elif None != re.search('jakarta.ws.rs.jakarta.ws.rs-api', service_implementation_classpath):
        print('Using jakarta code packages in API definition module.')
    else:
        print('Did not find javax or jakarta code packages in API definition module.')

    # update imports
    jmf.beautifyImports(proj_pom_path)

    # add licenses to files
    pl.prepend_licenses(descriptor, proj_gav.artifact_id, filesPath)

    # verify it compiles
    jmf.callMvnWithOptions(**mvn_opts, goal='clean install', file=proj_pom_path)
    jmf.callMvnWithOptions(**mvn_opts, goal='clean', file=proj_pom_path)