import com.emprogen.java.maven.functions as jmf
import com.emprogen.java.maven.yaml_functions as yf
import com.emprogen.java.maven.field_functions as ff
import com.emprogen.java.maven.service.jaxrs.service_impl_functions as sif
import com.emprogen.prepend_license as pl
import glob
import re

from com.emprogen.java.maven.models import Gav

def generate(descriptor: 'dict', archetypeGav: 'Gav' = Gav('com.emprogen', 'service-jaxrs-quarkus-p1-archetype', '0.0.2')
        , *, filesPath: 'str' = None, javaVersion: 'str' = '17', **kwargs) -> None:

    print('in service.jaxrs.quarkus.p2.v1.generate.py')
    print('javaVersion: ' + str(javaVersion))

    # define maven archetype used for this generator within script.
    archGav = archetypeGav

    # the maven groupId:artifactId:version for the code module to be generated
    projGav = yf.getGeneratedProjectGav(descriptor)

    # the gav for the maven module containing the jaxrs Interface from which the service will be generated.
    serviceInterfaceGavString = descriptor['serviceInterfaceGav']
    apiGav = yf.getGav(serviceInterfaceGavString)

    # the directory of the maven pom for the generated code. Usually at the directory root of project.
    projPomPath = projGav.artifactId + '/pom.xml'

    author = descriptor.get('author', 'Generated by Emprogen')

    # Geneate Maven project.
    # Set Maven archetype generation options.
    opts = {}
    opts['api_groupId'] = apiGav.groupId
    opts['api_artifactId'] = apiGav.artifactId
    opts['api_version'] = apiGav.version
    opts['jaxrs_service_interface'] = 'Template'
    opts['jaxrs_service_package'] = 'does.not.matter'
    print('service opts: ' + str(opts))

    #Enable mvn opts from command line
    mvn_options = jmf.captureContextualCommandLineOptions(kwargs.get('command_args', []), 'mvn')
    mvn_opts = {'mvn_options': mvn_options}
    opts.update(mvn_opts)

    print('mvn_options: ' + str(mvn_options))
    print('opts: ' + str(opts))

    # Actually generate the maven project
    jmf.generateMavenProject(archGav, projGav, author, **opts)
    print('Generated maven project with archetype: ' + str(archGav) + ' and projGav: ' + str(projGav))

    # get the java files, then winnow to ApiDefinition files.
    apiDefinitionFiles = []

    # get the gav from the serviceInterfaceGav (apiGav) and load the jar.
    # return a list of java class files in the jar that match the apiGav.
    apiGavPath = jmf.gav_to_path(str(apiGav))
    apiGavClassFiles = jmf.getFilesFromJar(apiGavPath, extensionFilter='.class')
    apiGavClassFileContents = {}
    print('apiGavClassFiles: ' + str(apiGavClassFiles))

    # Create a dictionary mapping from the java class name to the content of the class file for each java class file in the apiGav jar.
    for apiGavClassFile in apiGavClassFiles:
        javaClassName = apiGavClassFile.replace('/', '.').replace('.class', '')
        print('javaClassName: ' + str(javaClassName))
        contentFromJarClass = jmf.readContentFromJarClass(apiGavPath, javaClassName)
        print('contentFromJarClass: ' + str(contentFromJarClass))
        apiGavClassFileContents[javaClassName] = contentFromJarClass
    #print('apiGavClassFileContents: ' + str(apiGavClassFileContents))

    # Iterate over the java class file contents and find the ones that are ApiDefinition files.
    for className, classFileContent in apiGavClassFileContents.items():
        print('Checking if class is API definition: ' + str(className))
        if sif.isClassFileAnApiDefinition(classFileContent):
            print('Found API definition: ' + str(className))
            apiDefinitionFiles.append(className)

    print('apiDefinitionFiles: ' + str(apiDefinitionFiles))

    # process the API definition files to generate the service Impl and service classes.
    serviceImplementationClasspath = sif.processApiInterfaces(apiGav, projGav, apiDefinitionFiles, author=author)

    # add addtl dependencies to the pom.
    # if no items in optional dependencyGav, default {} for null safety
    for dependency in descriptor.get('dependencyGav', {}):
        print('adding dependency to pom: ' + dependency)
        jmf.addDependency(projPomPath, yf.getGav(dependency))

    # set java version to javaVersion
    jmf.removePomProperties(projPomPath, ['maven.compiler.source', 'maven.compiler.target'])
    jmf.addPomProperties(projPomPath, {'maven.compiler.source': javaVersion, 'maven.compiler.target': javaVersion})

    # set jaxrs package and java version based on the openapi3 module
    if None != re.search('javax.ws.rs.javax.ws.rs-api', serviceImplementationClasspath):
        print('Using javax in API definition module. Reducing Quarkus version in impl module to use javax instad of jakarta code packages. Reducing java version to 8.')
        # Fix java imports
        for javaFile in javaClassFilePaths:
            jmf.replaceTextInFile('import jakarta.', 'import javax.', javaFile)
        # Reduce Quarkus version
        jmf.removePomProperties(projPomPath, ['version.quarkus'])
        jmf.addPomProperties(projPomPath, {'version.quarkus': '2.16.8.Final'})

        # Reduce Java version to 8
        jmf.removePomProperties(projPomPath, ['maven.compiler.source', 'maven.compiler.target'])
        jmf.addPomProperties(projPomPath, {'maven.compiler.source': '8', 'maven.compiler.target': '8'})

    elif None != re.search('jakarta.ws.rs.jakarta.ws.rs-api', serviceImplementationClasspath):
        print('Using jakarta code packages in API definition module.')
    else:
        print('Did not find javax or jakarta code packages in API definition module.')

    # update imports
    jmf.beautifyImports(projPomPath)

    # add licenses to files
    pl.prependLicenses(descriptor, projGav.artifactId, filesPath)

    # verify it compiles
    jmf.callMvnWithOptions(**mvn_opts, goal='clean install', file=projPomPath)
    jmf.callMvnWithOptions(**mvn_opts, goal='clean', file=projPomPath)